### ISSUE TITLE
Reusable regex code

### ISSUE THREAD

**Issue by susannaanas** [artturimatias/GLAMpipe#14]
Here are some regex snippets that I have created:
Find names:
````
([A-ZÅÄÖ][\wåäö"-]+|\sde\b|\sla\b|\von\b)(\s[A-ZÅÄÖ"][\wåäö"-]*|\sde\b|\sla\b|\von\b)*
````
- Finds one or more adjoining names
- Scandinavian letters included
- Capital first letter
- de, la, von in the middle or beginning
- includes nicknames inside apostrophes
- includes hyphens

**Comment by artturimatias** [comment]
Example in "regexp extract" node
