### ISSUE TITLE
 Unexpected token ILLEGAL using back ticks instead of single quotes

### ISSUE THREAD

**Issue by timwaters** [artturimatias/GLAMpipe#7]
Hello,

I encountered an error loading up the system. It appears to be cause by the use of backticks? I changed these to single quotes and the system loaded okay.

I can make the patch into a pull request if you like... although im not sure if it is a fix or a workaround (in Ruby, for example backtick can be used to shell out a command \`echo foo\` )

```
tim@capricorn:~/projects/GLAMpipe$ nodejs glampipe.js 

/home/tim/projects/GLAMpipe/utils/sys-info.js:29
    value: `${Math.round(os.totalmem() / 1048576)} MB`
           ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/tim/projects/GLAMpipe/glampipe.js:5:18)

```

**Comment by artturimatias** [comment]
Hi,
and thanks for reporting.
Actually, those are not used any more. They were in NodeShift app template that I used. 
I'll remove these on next commit.
```

const contentTypes	= require('./utils/content-types');
const sysInfo		= require('./utils/sys-info');
```


Funny that error is not triggered on my Debian.
